name: 'units-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    env:
      INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }} # INDEXNOW_KEY env variable is only used in unit tests.
    steps:
      - uses: actions/checkout@v5
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          sitemap-location: 'https://bojieyang.github.io/sitemap.xml'
          since: 1
          since-unit: 'month'
          key: ${{ secrets.INDEXNOW_KEY }}

  test-atom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          sitemap-location: 'https://bojieyang.github.io/feed.xml'
          since: 2
          since-unit: 'month'
          key: ${{ secrets.INDEXNOW_KEY }}
